### PR TITLE
fix(716): X icon in New Route modal doesn't close the modal

### LINKED ISSUE #716: X icon in `New Route` modal doesn't close the modal
### Describe the Bug

`X` icon in New Route modal doesn't close the modal

### Steps to Reproduce the Bug or Issue

1. Start with a Camel Route integration type
2. Switch to a Kamelet type
3. Try to close the modal by using the `X` icon
4. The modal does't gets closed

### Screenshots or Videos

image

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

### PR DESCRIPTION
**Pull request by shivamG640**
fixes #716,

### CODE REVIEW

**Review by lordrip — APPROVED** [review]
Tested it locally, thanks @shivamG640 :ok_hand:

**Comment by shivamG640** [comment]
Hi @lordrip , 
There are 4 other models excluding this one and all of them have the onclose property with them!

**Comment by lordrip** [comment]
> Hi @lordrip , There are 4 other models excluding this one and all of them have the onclose property with them!

Ah, that's nice to read, cool then, we just had this one :ok_hand:

**Comment by lhein** [comment]
Awesome, thanks for taking care of this, Shivam!

**Pull request merged**
