### PR TITLE
fix: expression field loses the expression

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #722

### CODE REVIEW

**Comment by lhein** [comment]
I successfully tested locally and the expression is now kept...BUT...

the validation is now broken....see image below...

tomo_722

**Comment by apupier** [comment]
> the validation is now broken....see image below...

I do not reproduce on main branch so coming from (side-effect?) changes in this PR

**Comment by apupier** [comment]
> > the validation is now broken....see image below...
> 
> I do not reproduce on main branch so coming from (side-effect?) changes in this PR

Well, I do not reproduce neither with this PR...
So specific environment? Race condition?

**Comment by apupier** [comment]
> > > the validation is now broken....see image below...
> > 
> > 
> > I do not reproduce on main branch so coming from (side-effect?) changes in this PR
> 
> Well, I do not reproduce neither with this PR... So specific environment? Race condition?
> 
> EDIT: tried with Chrome and firefox

ah reproduced, need to change first the name, then the expression, then close the panel. And in fact, the validation is working, it is the name field which is not saved in this case

**Comment by lhein** [comment]
Ok, that is weird. I tried again now and I also cannot reproduce. So I guess we are fine to go.

**Review by lhein — DISMISSED** [review]
works fine

**Comment by apupier** [comment]
namepropertyNotSaved

**Comment by lhein** [comment]
Ah great, you catched it. I remember that I did test that way too and maybe this was the difference between today's and yesterday's test results.

**Comment by igarashitm** [comment]
Superseded by #726 
I'll extract the jest tests and submit another PR

**Pull request closed without merging**
