### PR TITLE
feat: Support ExpressionEditor for aggregate EIP

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #522

https://github.com/KaotoIO/kaoto-next/assets/265462/d7129c09-d5f4-40c2-97d1-11c684cb0176

I also plan to migrate step expression configuration like `setHeader` to be in a modal, but with a separate issue -  #523

### CODE REVIEW

**Comment by igarashitm** [comment]
Done for adding tests

**Comment by lordrip** [comment]
> I also plan to migrate step expression configuration like setHeader to be in a modal, but with a separate issue - https://github.com/KaotoIO/kaoto-next/issues/523

Ah, I was wondering why we had 2 ways to configure expressions :smile: . @igarashitm I think it's a good idea.

**Comment by lordrip** [comment]
The `saga` node that we see in the video is a `saga` processor, not the `saga` component.

**Review by lordrip — APPROVED** [review]
Awesome :muscle: :tada:

**Pull request merged**
