### PR TITLE
feat: Add camel catalog and schema

### PR DESCRIPTION
**Pull request by igarashitm**
### Build result
image

### CODE REVIEW

**Comment by lordrip** [comment]
@igarashitm could be possible to have a root `.json` file that tells us what's available?

I'm thinking about something like a `index.json`:

```json
{
  "componentCatalogs": [
    {
      "version": "4.0.0-RC1",
      "name": "Official Camel component catalog",
      "files": [
        "camel-catalog-aggregate-4.0.0-RC2.json"
      ]
    }
  ],
  "schemas": [
    {
      "version": "4.0.0-RC1",
      "name": "Camel 4.0.0-RC1",
      "file": "camel-yaml-dsl-4.0.0-RC2"
    },
    {
      "version": "1.12.1",
      "name": "Camel Integration",
      "file": "crd-schema-integration-1.12.1"
    },
    {
      "version": "1.12.1",
      "name": "Camel Kamelet",
      "file": "crd-schema-kamelet-1.12.1.json"
    },
    {
      "version": "1.12.1",
      "name": "Camel KameletBinding",
      "file": "crd-schema-kameletbinding-1.12.1.json"
    }
  ]
}
```

**Comment by igarashitm** [comment]
@lordrip Any request for kamelets? Here is the combined kamelets which is converted into JSON
[kamelets-aggregate-4.0.0-RC1.json.txt](https://github.com/KaotoIO/kaoto-next/files/12292238/kamelets-aggregate-4.0.0-RC1.json.txt)

**Comment by igarashitm** [comment]
BTW all the raw files extracted from Camel upstream are available in `packages/kaoto-catalog/assembly/target/camel` when you build. The kaoto maven plugin then consumes them and do combine, convert-to-JSON, etc.

**Comment by lordrip** [comment]
I think that it's good to move forward, the final test would be to see how the browser behaves with all the information loaded

**Comment by igarashitm** [comment]
maybe split the catalog into 4 files, component, dataformats, languages and model, I guess those don't have much benefit to be in a single file

**Comment by lordrip** [comment]
Yes @igarashitm, that's actually a good idea

**Comment by igarashitm** [comment]
OK done, the files created
* index.json
* camel-catalog-aggregate-components-4.0.0-RC2.json
* camel-catalog-aggregate-languages-4.0.0-RC2.json
* camel-catalog-aggregate-dataformats-4.0.0-RC2.json
* camel-catalog-aggregate-models-4.0.0-RC2.json
* camel-yaml-dsl-4.0.0-RC2.json
* crd-schema-kamelet-2.0.0.json
* crd-schema-pipe-2.0.0.json
* crd-schema-integration-2.0.0.json
* crd-schema-kameletbinding-2.0.0.json
* kamelets-aggregate-4.0.0-RC1.json


And the index.json contents
```json
{
  "catalogs" : {
    "models" : {
      "name" : "Aggregated Camel catalog for models",
      "version" : "4.0.0-RC2",
      "files" : [ "camel-catalog-aggregate-models-4.0.0-RC2.json" ]
    },
    "components" : {
      "name" : "Aggregated Camel catalog for components",
      "version" : "4.0.0-RC2",
      "files" : [ "camel-catalog-aggregate-components-4.0.0-RC2.json" ]
    },
    "languages" : {
      "name" : "Aggregated Camel catalog for languages",
      "version" : "4.0.0-RC2",
      "files" : [ "camel-catalog-aggregate-languages-4.0.0-RC2.json" ]
    },
    "dataformats" : {
      "name" : "Aggregated Camel catalog for dataformats",
      "version" : "4.0.0-RC2",
      "files" : [ "camel-catalog-aggregate-dataformats-4.0.0-RC2.json" ]
    }
  },
  "schemas" : [ {
    "name" : "Camel YAML DSL JSON schema",
    "version" : "4.0.0-RC2",
    "files" : [ "camel-yaml-dsl-4.0.0-RC2.json" ]
  }, {
    "name" : "Camel K Custom Resource JSON schema for Integration",
    "version" : "2.0.0",
    "files" : [ "crd-schema-integration-2.0.0.json" ]
  }, {
    "name" : "Camel K Custom Resource JSON schema for Kamelet",
    "version" : "2.0.0",
    "files" : [ "crd-schema-kamelet-2.0.0.json" ]
  }, {
    "name" : "Camel K Custom Resource JSON schema for KameletBinding",
    "version" : "2.0.0",
    "files" : [ "crd-schema-kameletbinding-2.0.0.json" ]
  }, {
    "name" : "Camel K Custom Resource JSON schema for Pipe",
    "version" : "2.0.0",
    "files" : [ "crd-schema-pipe-2.0.0.json" ]
  } ],
  "kamelets" : [ {
    "name" : "Aggregated Kamelet definitions in JSON",
    "version" : "4.0.0-RC1",
    "files" : [ "kamelets-aggregate-4.0.0-RC1.json" ]
  } ]
}
```

**Review by lordrip — APPROVED** [review]
LGTM. Maybe in the future, we would like to move the `Kameletes` property into the catalogs section of the `index.json` file, and somehow link that when using `KameletBindings` or `Pipes`, we would pick `Kamelets` from the `Kamelets` catalog.

In essence, something similar like we had in `kaoto-backend` as:

```json
{
  "dsls": [
    {
      "output": "true",
      "supportsResourceDescription": "true",
      "input": "true",
      "validationSchema": "/v1/capabilities/Integration/schema",
      "vocabulary": {
        "stepsName": "Steps"
      },
      "deployable": "true",
      "name": "Integration",
      "description": "An Integration defines a workflow of actions and steps.",
      "supportsMultipleFlows": "true",
      "stepKinds": "[CAMEL-CONNECTOR, EIP, EIP-BRANCH]"
    },
    {
      "output": "true",
      "supportsResourceDescription": "false",
      "input": "true",
      "validationSchema": "/v1/capabilities/Camel Route/schema",
      "vocabulary": {
        "stepsName": "Steps"
      },
      "deployable": "false",
      "name": "Camel Route",
      "description": "A camel route is a non deployable in cluster workflow of actions and steps.",
      "supportsMultipleFlows": "true",
      "stepKinds": "[CAMEL-CONNECTOR, EIP, EIP-BRANCH, CAMEL-REST-DSL, CAMEL-REST-VERB, CAMEL-REST-ENDPOINT]"
    },
    {
      "output": "true",
      "supportsResourceDescription": "true",
      "input": "true",
      "validationSchema": "/v1/capabilities/Kamelet/schema",
      "vocabulary": {
        "stepsName": "Steps"
      },
      "deployable": "true",
      "name": "Kamelet",
      "description": "A Kamelet is a snippet of a route. It defines meta building blocks or steps that can be reused on integrations.",
      "supportsMultipleFlows": "false",
      "stepKinds": "[CAMEL-CONNECTOR, EIP, EIP-BRANCH]"
    },
    {
      "output": "true",
      "supportsResourceDescription": "true",
      "input": "true",
      "default": "true",
      "validationSchema": "/v1/capabilities/KameletBinding/schema",
      "vocabulary": {
        "stepsName": "Steps"
      },
      "deployable": "true",
      "name": "KameletBinding",
      "description": "Kamelet Bindings are used to create simple integrations that link a start step to an end step with optional intermediate action steps.",
      "supportsMultipleFlows": "false",
      "stepKinds": "[KAMELET, KNATIVE]"
    }
  ]
}
```

Notice the `"stepKinds": "[KAMELET, KNATIVE]"` property, maybe we could use something like this to signal which steps can be used per schema.

**Pull request merged**
