### PR TITLE
fix(387): do not write empty string values to the source code unless …

### LINKED ISSUE #387: do not write empty string values to the source code unless its differing from the default value

### PR DESCRIPTION
**Pull request by shivamG640**
fixes #387,

Description:
These changes bring a clean source code by keeping only those parameters whose values differ from the default.

### CODE REVIEW

**Comment by lhein** [comment]
Tried to test your PR but I am not able to do any modifications on the config form. 

cannotConfigureAnyMore

**Comment by shivamG640** [comment]
> Tried to test your PR but I am not able to do any modifications on the config form.
> 
> cannotConfigureAnyMore [ cannotConfigureAnyMore ](https://private-user-images.githubusercontent.com/435853/288330799-ca8e8f29-d3d5-421b-b467-ce523a26bbd6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTA1NTUsIm5iZiI6MTcwMTg1MDI1NSwicGF0aCI6Ii80MzU4NTMvMjg4MzMwNzk5LWNhOGU4ZjI5LWQzZDUtNDIxYi1iNDY3LWNlNTIzYTI2YmJkNi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwODEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVjNTliNGU4MGYxYTgxZWE5OGQ3MjE4NWQ0N2I2Mjk5Y2U4MzM5NmM5NjZhMGUyNmU0NjViOGQ1YzkzYjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5vusP61ITMxRyeJdbZCTWPcIeWK0QtEAiE-74X29a0M) [ ](https://private-user-images.githubusercontent.com/435853/288330799-ca8e8f29-d3d5-421b-b467-ce523a26bbd6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTA1NTUsIm5iZiI6MTcwMTg1MDI1NSwicGF0aCI6Ii80MzU4NTMvMjg4MzMwNzk5LWNhOGU4ZjI5LWQzZDUtNDIxYi1iNDY3LWNlNTIzYTI2YmJkNi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwODEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjVjNTliNGU4MGYxYTgxZWE5OGQ3MjE4NWQ0N2I2Mjk5Y2U4MzM5NmM5NjZhMGUyNmU0NjViOGQ1YzkzYjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5vusP61ITMxRyeJdbZCTWPcIeWK0QtEAiE-74X29a0M)

Thanks for reviewing @lhein ,
I have to check what went wrong with this!

**Review by lhein — CHANGES_REQUESTED** [review]
We lose the ability to configure steps atm.

**Comment by lhein** [comment]
I am not sure I fully understand your logic. My idea would have been to not actively delete something from the source code but rather omit writing those values back to the source code at all if they match the defaults. If there is no default defined then we persist entries....of course...but only if there are really entries. Empty strings and alike aren't really entries.

**Comment by shivamG640** [comment]
https://github.com/KaotoIO/kaoto-next/assets/73224329/3ddff3bf-93e1-4d8a-8a8c-71a2700aafb0

**Comment by lhein** [comment]
ok, thats a great start. Pattern should however no longer show up after removing the content.

**Comment by lhein** [comment]
I can still see an empty parameters array put out into source code.

**Pull request merged**
